clear;
load data.txt;
h=figure;
%plot(data(:,1),data(:,2),'LineStyle','none','Marker','.','MarkerEdgeColor',[0.35 0.6 0]);
plot([data(:,1)';data(:,2)'] ,[data(:,3)';data(:,4)'],'Color',[0.7 0.7 0.7]);
axis equal;
hold on;
load intersect_c.txt;
plot(intersect_c(:,1),intersect_c(:,2),'.','Color','r');
hold on;
load intersect.txt;
plot(intersect(:,1),intersect(:,2),'.','Color','b');